// Auth
export const AUTH_USER = 'AUTH_USER'
export const AUTH_ERROR = 'AUTH_ERROR'

// Map
export const SET_VIEW = 'SET_VIEW'

// District
export const FETCH_DISTRICTS_SUCCESS = 'FETCH_DISTRICTS_SUCCESS'
export const FETCH_DISTRICTS_PENDING = 'FETCH_DISTRICTS_PENDING'
export const FETCH_DISTRICTS_FAILED = 'FETCH_DISTRICTS_FAILED'

// Categories
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS'
export const FETCH_CATEGORIES_PENDING = 'FETCH_CATEGORIES_PENDING'
export const FETCH_CATEGORIES_FAILED = 'FETCH_CATEGORIES_FAILED'

// Locations
export const FETCH_LOCATIONS = 'FETCH_LOCATIONS'
export const CLEAR_LOCATIONS = 'CLEAR_LOCATIONS'
